name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
      
      - name: Install Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install redis
      
      - name: Start Flask app
        run: |
          python app.py &
          sleep 5  # Wait for app to start
      
      - name: Run API tests
        env:
          FLASK_ENV: testing
          API_TOKEN: supersecrettoken
          FLASK_APP: app.py
        run: |
          pytest tests/test_app.py -v
      
      - name: Run frontend tests
        env:
          FLASK_ENV: testing
          API_TOKEN: supersecrettoken
          FLASK_APP: app.py
          CHROME_BIN: /usr/bin/chromium-browser
        run: |
          pytest tests/test_frontend.py -v 
          pytest tests/test_app.py -v 